// Generated by scripts/generate-cover-variants.mjs. Do not edit manually.

export type ImageMeta = {
  width: number;
  height: number;
};

export const imageMeta: Record<string, ImageMeta> = {
  "/assets/projects/orphanage-inspection-route-optimization/screenshots/aco-convergence-cluster0-400.webp":
    { width: 400, height: 239 },
  "/assets/projects/orphanage-inspection-route-optimization/screenshots/aco-convergence-cluster0-640.webp":
    { width: 640, height: 382 },
  "/covers/fraud-detection-ml-pipeline.svg": { width: 960, height: 640 },
  "/covers/juanda-airport-visitor-forecasting.svg": { width: 960, height: 640 },
  "/covers/la-crime-type-prediction.svg": { width: 960, height: 640 },
  "/covers/indo-transaction-nlp.svg": { width: 960, height: 640 },
  "/assets/projects/fraud-detection-ml-pipeline/pipeline-architecture.webp": {
    width: 1600,
    height: 1336,
  },
  "/assets/projects/fraud-detection-ml-pipeline/pr-auc-comparison.webp": {
    width: 1565,
    height: 1135,
  },
  "/assets/projects/fraud-detection-ml-pipeline/pr-curve.webp": {
    width: 1291,
    height: 1116,
  },
  "/assets/projects/fraud-detection-ml-pipeline/confusion-matrix.webp": {
    width: 903,
    height: 902,
  },
  "/assets/projects/juanda-airport-visitor-forecasting/screenshots/monthly-trend.webp":
    { width: 1156, height: 624 },
  "/assets/projects/juanda-airport-visitor-forecasting/screenshots/rf-forecast-vs-actual.webp":
    { width: 1156, height: 701 },
  "/assets/projects/la-crime-type-prediction/screenshots/correlation-heatmap.webp":
    { width: 601, height: 519 },
  "/assets/projects/fraud-detection-ml-pipeline/pipeline-architecture-400.webp":
    { width: 400, height: 334 },
  "/assets/projects/fraud-detection-ml-pipeline/pipeline-architecture-640.webp":
    { width: 640, height: 534 },
  "/assets/projects/fraud-detection-ml-pipeline/pr-auc-comparison-400.webp": {
    width: 400,
    height: 290,
  },
  "/assets/projects/fraud-detection-ml-pipeline/pr-auc-comparison-640.webp": {
    width: 640,
    height: 464,
  },
  "/assets/projects/fraud-detection-ml-pipeline/pr-curve-400.webp": {
    width: 400,
    height: 346,
  },
  "/assets/projects/fraud-detection-ml-pipeline/pr-curve-640.webp": {
    width: 640,
    height: 553,
  },
  "/assets/projects/fraud-detection-ml-pipeline/confusion-matrix-400.webp": {
    width: 400,
    height: 400,
  },
  "/assets/projects/fraud-detection-ml-pipeline/confusion-matrix-640.webp": {
    width: 640,
    height: 639,
  },
  "/assets/projects/juanda-airport-visitor-forecasting/screenshots/monthly-trend-400.webp":
    { width: 400, height: 216 },
  "/assets/projects/juanda-airport-visitor-forecasting/screenshots/monthly-trend-640.webp":
    { width: 640, height: 345 },
  "/assets/projects/juanda-airport-visitor-forecasting/screenshots/rf-forecast-vs-actual-400.webp":
    { width: 400, height: 243 },
  "/assets/projects/juanda-airport-visitor-forecasting/screenshots/rf-forecast-vs-actual-640.webp":
    { width: 640, height: 388 },
  "/assets/projects/sriwijayaair-review-sentiment/case-overview-400.webp": {
    width: 400,
    height: 248,
  },
  "/assets/projects/sriwijayaair-review-sentiment/case-overview-640.webp": {
    width: 640,
    height: 397,
  },
  "/assets/projects/sriwijayaair-review-sentiment/model-performance-400.webp": {
    width: 400,
    height: 154,
  },
  "/assets/projects/sriwijayaair-review-sentiment/model-performance-640.webp": {
    width: 640,
    height: 247,
  },
  "/assets/projects/sriwijayaair-review-sentiment/confusion-matrix-400.webp": {
    width: 400,
    height: 238,
  },
  "/assets/projects/sriwijayaair-review-sentiment/confusion-matrix-640.webp": {
    width: 640,
    height: 381,
  },
  "/assets/projects/sriwijayaair-review-sentiment/negative-review-signals-400.webp":
    { width: 400, height: 242 },
  "/assets/projects/sriwijayaair-review-sentiment/negative-review-signals-640.webp":
    { width: 640, height: 387 },
  "/assets/projects/sriwijayaair-review-sentiment/error-analysis-400.webp": {
    width: 400,
    height: 224,
  },
  "/assets/projects/sriwijayaair-review-sentiment/error-analysis-640.webp": {
    width: 640,
    height: 358,
  },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/01-help-hub-400.webp":
    { width: 400, height: 192 },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/01-help-hub-640.webp":
    { width: 640, height: 307 },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/02-guided-tour-400.webp":
    { width: 400, height: 192 },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/02-guided-tour-640.webp":
    { width: 640, height: 307 },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/03-resend-approval-400.webp":
    { width: 400, height: 192 },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/03-resend-approval-640.webp":
    { width: 640, height: 308 },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/01-microsoft-forms-po-request-400.webp":
    { width: 400, height: 225 },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/01-microsoft-forms-po-request-640.webp":
    { width: 640, height: 359 },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/03-b-simpel-document-distribution-400.webp":
    { width: 400, height: 190 },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/03-b-simpel-document-distribution-640.webp":
    { width: 640, height: 304 },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/01-home-400.webp":
    { width: 400, height: 236 },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/01-home-640.webp":
    { width: 640, height: 378 },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/02-preferences-400.webp":
    { width: 400, height: 236 },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/02-preferences-640.webp":
    { width: 640, height: 378 },
  "/assets/projects/bank-jatim-performance-dashboard/screenshots/Dashboard_Bank_Jatim_Pusat_page-0001-400.webp":
    { width: 400, height: 231 },
  "/assets/projects/bank-jatim-performance-dashboard/screenshots/Dashboard_Bank_Jatim_Pusat_page-0001-640.webp":
    { width: 640, height: 370 },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/04-power-bi-report-400.webp":
    { width: 400, height: 192 },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/04-power-bi-report-640.webp":
    { width: 640, height: 308 },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/02-sharepoint-list-po-database-400.webp":
    { width: 400, height: 191 },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/02-sharepoint-list-po-database-640.webp":
    { width: 640, height: 306 },
  "/assets/projects/orphanage-inspection-route-optimization/screenshots/public-project-link-400.webp":
    { width: 400, height: 255 },
  "/assets/projects/orphanage-inspection-route-optimization/screenshots/public-project-link-640.webp":
    { width: 640, height: 409 },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/03-results-400.webp":
    { width: 400, height: 236 },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/03-results-640.webp":
    { width: 640, height: 378 },
  "/assets/profile/profile_avatar-96.webp": { width: 96, height: 96 },
  "/assets/profile/profile_avatar-160.webp": { width: 160, height: 160 },
  "/assets/profile/profile_photo-640.webp": { width: 640, height: 853 },
  "/assets/profile/profile_photo-960.webp": { width: 960, height: 1280 },
  "/assets/profile/profile_photo.webp": { width: 1200, height: 1600 },
  "/assets/projects/bank-jatim-performance-dashboard/screenshots/Dashboard_Bank_Jatim_Pusat_page-0001.webp":
    {
      width: 1400,
      height: 810,
    },
  "/assets/projects/bank-jatim-performance-dashboard/screenshots/Dashboard_Bank_Jatim_Pusat_page-0002.webp":
    {
      width: 1400,
      height: 810,
    },
  "/assets/projects/bank-jatim-performance-dashboard/screenshots/Dashboard_Bank_Jatim_Pusat_page-0003.webp":
    {
      width: 1400,
      height: 810,
    },
  "/assets/projects/bank-jatim-performance-dashboard/screenshots/Dashboard_Bank_Jatim_Pusat_page-0004.webp":
    {
      width: 1400,
      height: 810,
    },
  "/assets/projects/orphanage-inspection-route-optimization/screenshots/aco-convergence-cluster0.webp":
    { width: 989, height: 590 },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/01-help-hub.webp":
    {
      width: 1386,
      height: 665,
    },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/02-guided-tour.webp":
    {
      width: 1244,
      height: 597,
    },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/03-resend-approval.webp":
    {
      width: 1400,
      height: 673,
    },
  "/assets/projects/kpc-ideku-v3-dotnet-stabilization/screenshots/04-power-bi-report.webp":
    {
      width: 1257,
      height: 604,
    },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/01-microsoft-forms-po-request.webp":
    {
      width: 830,
      height: 466,
    },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/02-sharepoint-list-po-database.webp":
    {
      width: 1400,
      height: 669,
    },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/02-sharepoint-list-po-database-home.webp":
    {
      width: 1080,
      height: 516,
    },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/03-b-simpel-document-distribution.webp":
    {
      width: 1105,
      height: 525,
    },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/04-power-automate-intake-document-check-flow.webp":
    {
      width: 356,
      height: 773,
    },
  "/assets/projects/kpc-power-automate-po-automation/screenshots/05-power-automate-hse-approval-b-simpel-flow.webp":
    {
      width: 352,
      height: 785,
    },
  "/assets/projects/la-crime-type-prediction/ml_workflow_diagram.svg": {
    width: 1440,
    height: 760,
  },
  "/assets/projects/medimate-medicine-reminder-app/screenshots/01-home.webp": {
    width: 390,
    height: 844,
  },
  "/assets/projects/medimate-medicine-reminder-app/screenshots/02-add-medicine.webp":
    {
      width: 390,
      height: 844,
    },
  "/assets/projects/medimate-medicine-reminder-app/screenshots/03-detail-medicine.webp":
    {
      width: 390,
      height: 844,
    },
  "/assets/projects/orphanage-inspection-route-optimization/screenshots/public-project-link.webp":
    {
      width: 1400,
      height: 894,
    },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/01-home.webp": {
    width: 1400,
    height: 826,
  },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/02-preferences.webp":
    {
      width: 1400,
      height: 826,
    },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/03-results.webp":
    { width: 1400, height: 826 },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/04-explore-results.webp":
    {
      width: 1400,
      height: 826,
    },
  "/assets/projects/scent2me-perfume-recommendation/screenshots/04-explore.webp":
    { width: 1400, height: 826 },
  "/assets/projects/sriwijayaair-review-sentiment/case-overview.webp": {
    width: 1400,
    height: 869,
  },
  "/assets/projects/sriwijayaair-review-sentiment/model-performance.webp": {
    width: 1400,
    height: 540,
  },
  "/assets/projects/sriwijayaair-review-sentiment/confusion-matrix.webp": {
    width: 1400,
    height: 833,
  },
  "/assets/projects/sriwijayaair-review-sentiment/negative-review-signals.webp":
    { width: 1400, height: 846 },
  "/assets/projects/sriwijayaair-review-sentiment/error-analysis.webp": {
    width: 1400,
    height: 783,
  },
  "/assets/logos/organization/hmsi-64.webp": { width: 64, height: 64 },
  "/assets/logos/organization/hmsi-128.webp": { width: 128, height: 128 },
  "/assets/logos/organization/its-h64.webp": { width: 143, height: 64 },
  "/assets/logos/organization/its-h128.webp": { width: 286, height: 128 },
  "/assets/logos/organization/kpc-64.webp": { width: 64, height: 64 },
  "/assets/logos/organization/kpc-128.webp": { width: 128, height: 128 },
};
